MainApp/MainApp/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using MainApp.Authorization;
using MainApp.EntityFramework;
using MainApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MainApp.Controllers
{
    public class CompanyController : Controller
    {

        private readonly DataContext _context;
        public CompanyController(DataContext context)
        {
            _context = context;
            Console.WriteLine("CompanyController: " + _context.JobOffers.Count());
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index([FromQuery(Name = "search")] string searchString)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            List<Company> searchResult;

            if (string.IsNullOrEmpty(searchString))
                searchResult = await _context.Companies.ToListAsync();
            else
                searchResult = await _context
                .Companies
                .Where(o => o.Name.Contains(searchString, StringComparison.OrdinalIgnoreCase))
                .ToListAsync();
            
            if(role == Role.ADMIN)
            {
                return View("IndexAdmin", searchResult);
            }
            return View("IndexHRAndCandidate", searchResult);
        }

        [Authorize]
        public async Task<ActionResult> Delete(int? id)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            if (role != Role.ADMIN)
                return new UnauthorizedResult();
            if (id==null)
            {
                return NotFound();
            }
            Company company = await _context.Companies.FindAsync(id);
            if(company==null)
            {
                return NotFound();
            }
            return View(company);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            if (role != Role.ADMIN)
                return new UnauthorizedResult();
            Company company = _context.Companies.Find(id);
            if(company==null)
            {
                return NotFound();
            }
            _context.Companies.Remove(company);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [Authorize]
        public async Task<ActionResult> Create()
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            if (role != Role.ADMIN)
                return new UnauthorizedResult();
            return View();
        }

        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> CreateConfirmed(Company company)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            if (!ModelState.IsValid)
            {
                return View();
            }
            if (role != Role.ADMIN)
                return new UnauthorizedResult();
            await _context.Companies.AddAsync(company);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [Authorize]
        public async Task<ActionResult> Edit(int? id)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            if (role != Role.ADMIN)
                return new UnauthorizedResult();
            if (id==null)
            {
                return NotFound();
            }
            Company company = await _context.Companies.FindAsync(id);
            if(company==null)
            {
                return NotFound();
            }
            return View(company);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> EditConfirmed(Company company)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            if (role != Role.ADMIN)
                return new UnauthorizedResult();
            if (!ModelState.IsValid)
            {
                return View();
            }
            _context.Companies.Update(company);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index"); 
        }

        public async Task<IActionResult> Details(int id)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            if (role != Role.ADMIN)
                return new UnauthorizedResult();
            var model = _context.Companies.Find(id);
            return View("Details", model);
        }
    }
}

MainApp/MainApp/Controllers/JobOfferController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MainApp.Models;
using MainApp.EntityFramework;
using Microsoft.EntityFrameworkCore;
using MainApp.Authorization;
using Microsoft.AspNetCore.Authorization;

namespace MainApp.Controllers
{
    public class JobOfferController : Controller
    {
        private readonly DataContext _context;

        public JobOfferController(DataContext context)
        {
            _context = context;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index([FromQuery(Name = "search")] string searchString)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            List<JobOffer> searchResult;
            if (string.IsNullOrEmpty(searchString))
            {
                searchResult = await _context.JobOffers
                    .Include(x => x.HR)
                    .Include(x => x.HR.Company)
                    .ToListAsync();
            }
            else
            {
                searchResult = await _context
                    .JobOffers
                    .Include(x => x.HR)
                    .Include(x => x.HR.Company)
                    .Where(o => o.JobTitle.Contains(searchString, StringComparison.OrdinalIgnoreCase)
                    || o.HR.Company.Name.Contains(searchString, StringComparison.OrdinalIgnoreCase))
                    .ToListAsync();
            }
            string email = AuthorizationTools.GetEmail(User);
            if (role == Role.HR)
            {
                JobOfferIndexHRView jobOfferIndexHRView = new JobOfferIndexHRView();
                jobOfferIndexHRView.Offers = searchResult;
                HR us = _context.HRs.Where(h => h.EmailAddress == email).First();
                jobOfferIndexHRView.HR = us;
                return View("IndexHR", jobOfferIndexHRView);
            }
            else if (role == Role.CANDIDATE)
            {
                JobOfferIndexCandidateView jobOfferIndexCandidateView = new JobOfferIndexCandidateView();
                jobOfferIndexCandidateView.Offers = searchResult;
                Candidate us = _context.Candidates.Where(c => c.EmailAddress == email).First();
                jobOfferIndexCandidateView.Candidate = us;
                return View("IndexCandidate", jobOfferIndexCandidateView);
            }
            //role == Role.ADMIN
            return View("IndexAdmin", searchResult);
        }
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            if (role == Role.CANDIDATE)
                return new UnauthorizedResult();
            if (id == null)
            {
                return BadRequest($"id shouldn't be null");
            }
            var offer = await _context.JobOffers.FirstOrDefaultAsync(x => x.Id == id.Value);
            if (offer == null)
            {
                return NotFound($"offer not found in DB");
            }
            if (role == Role.HR)
            {
                string email = AuthorizationTools.GetEmail(User);
                HR us = _context.HRs.Where(h => h.EmailAddress == email).First();
                if (us.Id != offer.HR.Id)
                    return new UnauthorizedResult();
            }

            return View(offer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Edit(JobOffer model)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            if (role == Role.CANDIDATE)
                return new UnauthorizedResult();

            if (!ModelState.IsValid || (model.SalaryFrom != null && model.SalaryTo != null && model.SalaryFrom > model.SalaryTo))
            {
                return View();
            }

            var offer = await _context.JobOffers.FirstOrDefaultAsync(x => x.Id == model.Id);
            if (role == Role.HR)
            {
                string email = AuthorizationTools.GetEmail(User);
                HR us = _context.HRs.Where(h => h.EmailAddress == email).First();
                if (us.Id != offer.HR.Id)
                    return new UnauthorizedResult();
            }
            offer.JobTitle = model.JobTitle;
            offer.Description = model.Description;
            offer.Location = model.Location;
            offer.SalaryFrom = model.SalaryFrom;
            offer.SalaryTo = model.SalaryTo;
            offer.ValidUntil = model.ValidUntil;
            _context.Update(offer);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", new { id = model.Id });
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Delete(int? id)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            if (role == Role.CANDIDATE)
                return new UnauthorizedResult();

            if (id == null)
            {
                return BadRequest($"id should not be null");
            }
            var offer = await _context.JobOffers.Include(x => x.HR).FirstOrDefaultAsync(x => x.Id == id.Value);
            if (role == Role.HR)
            {
                string email = AuthorizationTools.GetEmail(User);
                HR us = _context.HRs.Where(h => h.EmailAddress == email).First();
                if (us.Id != offer.HR.Id)
                    return new UnauthorizedResult();
            }
            List<Application> apps = await _context.JobApplications.Where(x => x.JobOffer == offer).ToListAsync();
            _context.JobApplications.RemoveRange(apps);
            _context.JobOffers.Remove(offer);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [Authorize]
        public async Task<ActionResult> Create()
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            if (role != Role.HR)
                return new UnauthorizedResult();
            var model = new JobOffer();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Create(JobOffer model)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            if (role != Role.HR)
                return new UnauthorizedResult();

            if (!ModelState.IsValid || (model.SalaryFrom != null && model.SalaryTo!= null && model.SalaryFrom > model.SalaryTo))
            {
                return View(model);
            }
            string email = AuthorizationTools.GetEmail(User);
            HR us = _context.HRs.Where(h => h.EmailAddress == email).First();
            JobOffer jo = new JobOffer
            {
                Description = model.Description,
                JobTitle = model.JobTitle,
                Location = model.Location,
                SalaryFrom = model.SalaryFrom,
                SalaryTo = model.SalaryTo,
                ValidUntil = model.ValidUntil,
                Created = DateTime.Now,
                HR = us
            };

            await _context.JobOffers.AddAsync(jo);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            var offer = await _context.JobOffers
                .Include(x => x.HR)
                .Include(x => x.HR.Company)
                .FirstOrDefaultAsync(x => x.Id == id);
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            if (role == Role.HR)
            {
                JobOfferDetailsHRView jobOfferDetailsHRView = new JobOfferDetailsHRView();
                jobOfferDetailsHRView.Offer = offer;
                string email = AuthorizationTools.GetEmail(User);
                HR us = _context.HRs.Where(h => h.EmailAddress == email).First();
                jobOfferDetailsHRView.HR = us;
                jobOfferDetailsHRView.Applications = await _context.JobApplications.Where(ja => ja.JobOffer == offer).ToListAsync();
                return View("DetailsHR", jobOfferDetailsHRView);
            }
            if (role == Role.ADMIN)
                return View("DetailsAdmin", offer);
            return View("DetailsCandidate", offer);
        }
    }
}

MainApp/MainApp/Views/Company/Create.cshtml
@model MainApp.Models.Company

@{
    ViewData["Title"] = "Create";
}

<h2>New</h2>

<h4>Company</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MainApp/MainApp/Views/Company/Delete.cshtml
@model MainApp.Models.Company

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Company</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MainApp/MainApp/Views/Company/Details.cshtml
@model MainApp.Models.Company

@{
    ViewData["Title"] = @Model.Name;
}

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="d-flex align-items-center">
            <div class="pr-3" style="font-size: 25px">
                <a href="@Url.Action("Index", "Company")">
                    <i class="fa fa-chevron-circle-left"></i>
                </a>
            </div>
            <h3 class="mb-1">
                Details
            </h3>
        </div>
    </div>
    <div class="pt-2">
        <div>
            <div class="offer-details">
                <h4 class="mb-0 mt-2">@Model.Name</h4>
                <label>Name:</label>
                <div class="content">@Model.Name</div>
                <div class="pt-4">
                    <a asp-action="Edit" asp-route-id="@Model.Id">
                        <button class="btn btn-rounded btn-primary mx-2">
                            <i class="fa fa-edit pr-2"></i>
                            Edit
                        </button>
                    </a>
                    <button class="btn btn-rounded btn-danger mx-2"
                            data-toggle="modal"
                            data-target="#confirm-delete">
                        <i class="fa fa-trash pr-2"></i>
                        Delete
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete Employee</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="font-weight-bold mb-0">Are you sure you want to delete this?</p>
                <p class="text-danger mb-0"><small>This action cannot be undone.</small></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-rounded" data-dismiss="modal">
                    <i class="fa fa-chevron-left pr-2"></i>
                    Cancel
                </button>
                @using (Html.BeginForm("Delete", "Company", new { Model.Id }, FormMethod.Post, null, new { style = "display:inline;" }))
                {
                    @Html.AntiForgeryToken()
                    <button type="submit" class="btn btn-rounded btn-danger">
                        <i class="fa fa-trash pr-2"></i>
                        Delete
                    </button>
                }
            </div>
        </div>
    </div>
</div>

MainApp/MainApp/Views/Company/Edit.cshtml
@model MainApp.Models.Company
@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-sm-12">
        <h2>Edit company information</h2>
        @using (Html.BeginForm("Create"))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.Id)
            <div class="form-group">
                @Html.LabelFor(m => m.Name)
                @Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.Name)
            </div>
            <a asp-area="" asp-controller="Company" asp-action="Index">
                <button type="button" class="btn btn-rounded btn-secondary mr-2">
                    <i class="fa fa-chevron-left pr-2"></i>
                    Cancel
                </button>
            </a>
            <button type="submit" class="btn btn-rounded btn-primary" id="submit">
                <i class="fa fa-check pr-2"></i>
                Save
            </button>
        }
    </div>
</div>
<div class="modal" tabindex="-1" role="dialog" id="myModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Company saved</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Company data was saved</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $(function () {
            $('#submit').on('click', function (evt) {
                evt.preventDefault();
                $.post('', $('form').serialize(), function () {
                    $('#myModal').modal();
                });
            });
        });
    </script>
}

MainApp/MainApp/Views/Company/IndexAdmin.cshtml
@model IEnumerable<MainApp.Models.Company>

@{
    ViewData["Title"] = "Companies";
}

<div class="row page-box">
    <div class="col-sm-12">
        <div class="table-title">
            <div class="row">
                <div class="col-12 col-md-4 d-flex align-items-center py-2">
                    <h3 class="font-weight-bold mb-0">
                        Company list
                    </h3>
                    <div>
                        <span class="badge badge-pill badge-primary align-top">
                            @Model.Count()
                        </span>
                    </div>
                </div>
                <div class="col-12 col-md-4 py-2">
                    @using (Html.BeginForm("Index", "Company", FormMethod.Get))
                    {
                        <div class="input-group search-input"
                             style="border-radius: 20px">
                            <input name="search"
                                   type="text"
                                   class="form-control"
                                   placeholder="Search by name.."
                                   aria-label="Search by name"
                                   aria-describedby="button-search">
                            <div class="input-group-append">
                                <button id="button-search"
                                        class="btn btn-primary"
                                        type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>
                    }
                </div>
                <div class="col-12 col-sm-4 text-right py-2">
                    <a href="@Url.Action("Create", "Company")">
                        <button class="btn btn-rounded btn-outline-primary"
                                data-toggle="modal">
                            <i class="fa fa-plus pr-3"></i>
                            Create new company
                        </button>
                    </a>
                </div>
            </div>
        </div>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">Company name</th>
                    <th style="width: 20px"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var hr in Model.OrderBy(h => h.Name))
                {
                <tr>
                    <td>@Html.ActionLink(hr.Name, "Details", new { id = hr.Id })</td>
                    <td>
                        <a href="@Url.Action("Edit", "Company", new { id = hr.Id })"
                           class="text-primary">
                            <i class="fa fa-edit"
                               title="Edit"></i>
                        </a>
                    </td>
                </tr>

                }

            </tbody>
        </table>

    </div>
</div>

MainApp/MainApp/Views/Company/IndexHRAndCandidate.cshtml
@model IEnumerable<MainApp.Models.Company>

@{
    ViewData["Title"] = "Companies";
}

<div class="row page-box">
    <div class="col-sm-12">
        <div class="table-title">
            <div class="row">
                <div class="col-12 col-md-4 d-flex align-items-center py-2">
                    <h3 class="font-weight-bold mb-0">
                        Company list
                    </h3>
                    <div>
                        <span class="badge badge-pill badge-primary align-top">
                            @Model.Count()
                        </span>
                    </div>
                </div>
                <div class="col-12 col-md-4 py-2">
                    @using (Html.BeginForm("Index", "Company", FormMethod.Get))
                    {
                        <div class="input-group search-input"
                             style="border-radius: 20px">
                            <input name="search"
                                   type="text"
                                   class="form-control"
                                   placeholder="Search by name.."
                                   aria-label="Search by name"
                                   aria-describedby="button-search">
                            <div class="input-group-append">
                                <button id="button-search"
                                        class="btn btn-primary"
                                        type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">Company name</th>
                    <th style="width: 20px"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var hr in Model.OrderBy(h => h.Name))
                {
                <tr>
                    <td>@Html.ActionLink(hr.Name, "Index", "JobOffer", new { search = hr.Name }, null)</td>
                </tr>

                }

            </tbody>
        </table>

    </div>
</div>