MainApp/MainApp/Controllers/ApplicationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MainApp.BlobStorage;
using MainApp.Authorization;
using MainApp.EntityFramework;
using MainApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SendGrid;
using SendGrid.Helpers.Mail;
using System.IO;

namespace MainApp.Controllers
{
    public class ApplicationController : Controller
    {
        private readonly DataContext _context;
        private readonly BlobStorageService _blob;
        private readonly IHostingEnvironment _env;

        public ApplicationController(DataContext context, BlobStorageService blob, IHostingEnvironment env)
        {
            _context = context;
            _blob = blob;
            _env = env;
        }

        /// GET Application/Index
        /// <summary>
        /// Shows list of applications
        /// </summary>
        /// <remarks>
        /// Shows list of applications proper for user role.
        /// </remarks>
        /// <param name="searchString">String containing search terms from View</param>
        /// <returns>List of applications</returns>
        [Route("Index")]
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index([FromQuery(Name = "search")] string searchString)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            List<Application> searchResult;

            if (string.IsNullOrEmpty(searchString))
                searchResult = await _context.JobApplications
                     .Include(x => x.JobOffer)
                     .Include(x => x.JobOffer.HR)
                     .Include(x => x.JobOffer.HR.Company)
                     .Include(x => x.Comments)
                     .ToListAsync();
            else
            {
                searchResult = await _context
                    .JobApplications
                    .Include(x => x.JobOffer)
                    .Include(x => x.JobOffer.HR)
                    .Include(x => x.JobOffer.HR.Company)
                    .Include(x => x.Comments)
                    .Where(o => o.LastName.Contains(searchString, StringComparison.OrdinalIgnoreCase))
                    .ToListAsync();
            }
            if (role == Role.HR)
            {
                string email = AuthorizationTools.GetEmail(User);
                HR us = _context.HRs.Where(h => h.EmailAddress == email).First();
                searchResult = searchResult.Where(a => a.JobOffer.HR == us).ToList();
                return View("IndexHR", searchResult);
            }
            else if (role == Role.CANDIDATE)
            {
                string email = AuthorizationTools.GetEmail(User);
                Candidate us = _context.Candidates.Where(c => c.EmailAddress == email).First();
                searchResult = searchResult.Where(a => a.Candidate == us).ToList();
                return View("IndexCandidate", searchResult);
            }
            return View("IndexAdmin", searchResult);
        }

        
        [Authorize]
        [ApiExplorerSettings(IgnoreApi = true)]
        public async Task<ActionResult> Create(int id)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));

            if (role != Role.CANDIDATE)
                return new UnauthorizedResult();
            JobOffer offer = _context.JobOffers.Where(o => o.Id == id).First();
            string email = AuthorizationTools.GetEmail(User);
            Candidate candidate = _context.Candidates.Where(c => c.EmailAddress == email).First();
            var model = new Application()
            {
                FirstName = candidate.FirstName,
                LastName = candidate.LastName,
                PhoneNumber = candidate.PhoneNumber,
                CvUrl = "TODO",
                EmailAddress = email,
                JobOffer = offer,
                Candidate = candidate
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Create([Bind("Id, FirstName, LastName, PhoneNumber, EmailAddress, ContactAgreement, CvUrl, File, State, JobOffer, Candidate")] Application model)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));

            if (role != Role.CANDIDATE)
                return new UnauthorizedResult();
            JobOffer offer = _context.JobOffers.Include(x=>x.HR).Where(o => o.Id == model.Id).First();
            string email = AuthorizationTools.GetEmail(User);
            Candidate candidate = _context.Candidates.Where(c => c.EmailAddress == email).First();
            if (!ModelState.IsValid)
            {
                return View();
            }

            var uploads = Path.Combine(_env.WebRootPath, "uploads");
            bool exists = Directory.Exists(uploads);
            if (!exists)
               Directory.CreateDirectory(uploads);            
            var fileName = Path.GetFileName(model.File.FileName);
            var fileStream = new FileStream(Path.Combine(uploads, model.File.FileName), FileMode.Create);
            string mimeType = model.File.ContentType;
            byte[] fileData = null;
            using (var memoryStream = new MemoryStream())
            {
               model.File.CopyTo(memoryStream);
               fileData = memoryStream.ToArray();
            }            
            model.CvUrl = _blob.UploadFileToBlob(model.File.FileName, fileData, mimeType);

            Application application = new Application()
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                EmailAddress = model.EmailAddress,
                PhoneNumber = model.PhoneNumber,
                CvUrl = model.CvUrl,
                ContactAgreement = model.ContactAgreement,
                Comments = model.Comments,
                Candidate = candidate,
                JobOffer = offer,
                State = "Pending"
            };


            await _context.JobApplications.AddAsync(application);
            await _context.SaveChangesAsync();

            var apiKey = "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";
            var client = new SendGridClient(apiKey);
            var from = new EmailAddress("290444@pw.edu.pl", "HRMiniApp");
            var subject = "New application";
            var to = new EmailAddress(offer.HR.EmailAddress);
            var plainTextContent = "";
            var htmlContent = $"<strong>Your Job Offer received new Application: <a href=https://localhost:5001/Application/Details/{ model.Id}>link</a> </strong>";
            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
            var attachment = new Attachment()
            {
                Content = Convert.ToBase64String(fileData),
                Filename = "cv.pdf"
            };
            msg.AddAttachment(attachment);
            var response = await client.SendEmailAsync(msg);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> CreateCommentAjax(ApplicationWithComment model)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            if(model.CommentText == "")
                RedirectToAction("Details", new { id = model.Id });
            if (role != Role.HR)
                return new UnauthorizedResult();
            Application app = _context.JobApplications
                .Include(x => x.Comments)
                .Include(x => x.JobOffer)
                .Include(x => x.JobOffer.HR)
                .Where(a => a.Id == model.Id).FirstOrDefault();
            string email = AuthorizationTools.GetEmail(User);
            HR hr = _context.HRs.Where(c => c.EmailAddress == email).First();
            if(app.JobOffer.HR != hr)
                return new UnauthorizedResult();

            Comment comm = new Comment() { Text = model.CommentText, Application = app };

            await _context.Comments.AddAsync(comm);
            await _context.SaveChangesAsync();

            return RedirectToAction("Details", new { id = model.Id });
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> DeleteCommentAjax(int id)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));

            if (role != Role.HR)
                return new UnauthorizedResult();
            Comment comment = _context.Comments
                .Include(x => x.Application)
                .Include(x => x.Application.JobOffer)
                .Include(x => x.Application.JobOffer.HR)
                .Where(a => a.Id == id).FirstOrDefault();
            if (comment == null)
                return new UnauthorizedResult();
            Application app = comment.Application;
            string email = AuthorizationTools.GetEmail(User);
            HR hr = _context.HRs.Where(c => c.EmailAddress == email).First();
            if (comment.Application.JobOffer.HR != hr)
                return new UnauthorizedResult();

MainApp/MainApp/Views/Application/Create.cshtml
@model MainApp.Models.Application

@{
    ViewData["Title"] = "Create";
}

@*This won't work (yet) - we need JobOffer id and Candidate id,
    they should be supplied in the Application controller.
    They won't change in this view, but will influence the view:
    JobOffer will be passed as hidden argument in form, and
    Candidate will supply default values for the form fields
    and will be passed as hidden argument in form*@
<div class="row page-box">
    <div class="col-sm-12">
        <h2>New application</h2>
        @using (Html.BeginForm("Create", "Application", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                @Html.LabelFor(m => m.FirstName)
                @Html.EditorFor(m => m.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.LastName)
                @Html.EditorFor(m => m.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.PhoneNumber)
                @Html.EditorFor(m => m.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.PhoneNumber, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.EmailAddress)
                @Html.EditorFor(m => m.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.EmailAddress, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.TextBoxFor(m => m.File, new { type = "file" })
                @Html.ValidationMessageFor(m => m.File)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.ContactAgreement)
                @Html.EditorFor(m => m.ContactAgreement, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.ContactAgreement, "", new { @class = "text-danger" })
            </div>
            <a asp-area="" asp-controller="JobOffer" asp-action="Index">
                <button type="button" class="btn btn-rounded btn-secondary mr-2">
                    <i class="fa fa-chevron-left pr-2"></i>
                    Cancel
                </button>
            </a>
            <button type="submit" class="btn btn-rounded btn-primary">
                <i class="fa fa-check pr-2"></i>
                Save
            </button>
        }
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MainApp/MainApp/Views/Application/DetailsCandidate.cshtml
@model MainApp.Models.Application

@{
    ViewData["Title"] = Model.FirstName + " " + Model.LastName;
}

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="d-flex align-items-center">
            <div class="pr-3" style="font-size: 25px">
                <a href="@Url.Action("Index", "Application")">
                    <i class="fa fa-chevron-circle-left"></i>
                </a>
            </div>
            <h3 class="mb-1">
                Details
            </h3>
        </div>
    </div>
    <div class="pt-2">
        <div>
            <div class="offer-details">
                <h4 class="mb-0 mt-2">@(Model.JobOffer.JobTitle + ": " + Model.LastName + "'s Application")</h4>
                <label>Job offer:</label>
                <div class="content">@Model.JobOffer.JobTitle</div>
                <label>Company:</label>
                <div class="content">@Model.JobOffer.HR.Company.Name</div>
                <label>First name:</label>
                <div class="content">@Model.FirstName</div>
                <label>Last name:</label>
                <div class="content">@Model.LastName</div>
                <label>Email adress:</label>
                <div class="content">@Model.EmailAddress</div>
                <label>Phone number:</label>
                <div class="content">@Model.PhoneNumber</div>
                <label>Cv url:</label>
                <div class="content">@Model.CvUrl</div>
                <label>Contact agreement:</label>
                <div class="content">@Model.ContactAgreement</div>
                <label>Status:</label>
                <div class="content">@Model.State</div>
                @if (Model.State == "Pending")
                {
                    <div class="pt-4">
                        <a asp-action="Edit" asp-route-id="@Model.Id">
                            <button class="btn btn-rounded btn-primary mx-2">
                                <i class="fa fa-edit pr-2"></i>
                                Edit
                            </button>
                        </a>
                        <button class="btn btn-rounded btn-danger mx-2"
                                data-toggle="modal"
                                data-target="#confirm-delete">
                            <i class="fa fa-trash pr-2"></i>
                            Delete
                        </button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete Application</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="font-weight-bold mb-0">Are you sure you want to delete this?</p>
                <p class="text-danger mb-0"><small>This action cannot be undone.</small></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-rounded" data-dismiss="modal">
                    <i class="fa fa-chevron-left pr-2"></i>
                    Cancel
                </button>
                @using (Html.BeginForm("Delete", "Application", new { Model.Id }, FormMethod.Post, null, new { style = "display:inline;" }))
                {
                    @Html.AntiForgeryToken()
                    <button type="submit" class="btn btn-rounded btn-danger">
                        <i class="fa fa-trash pr-2"></i>
                        Delete
                    </button>
                }
            </div>
        </div>
    </div>
</div>

MainApp/MainApp/Views/Application/DetailsHR.cshtml
@model MainApp.Models.ApplicationWithComment

@{
    ViewData["Title"] = Model.FirstName + " " + Model.LastName;
}

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="d-flex align-items-center">
            <div class="pr-3" style="font-size: 25px">
                <a href="@Url.Action("Index", "Applications")">
                    <i class="fa fa-chevron-circle-left"></i>
                </a>
            </div>
            <h3 class="mb-1">
                Details
            </h3>
        </div>
    </div>
    <div class="pt-2">
        <div>
            <div class="offer-details">
                <h4 class="mb-0 mt-2">@(Model.JobOffer.JobTitle + ": " + Model.LastName + "'s Application")</h4>
                <label>Job offer:</label>
                <div class="content">@Model.JobOffer.JobTitle</div>
                <label>Company:</label>
                <div class="content">@Model.JobOffer.HR.Company.Name</div>
                <label>First name:</label>
                <div class="content">@Model.FirstName</div>
                <label>Last name:</label>
                <div class="content">@Model.LastName</div>
                <label>Email adress:</label>
                <div class="content">@Model.EmailAddress</div>
                <label>Phone number:</label>
                <div class="content">@Model.PhoneNumber</div>
                <label>Cv url:</label>
                <div class="content">@Model.CvUrl</div>
                <label>Contact agreement:</label>
                <div class="content">@Model.ContactAgreement</div>
                <label>Status:</label>
                <div class="content">@Model.State</div>
            </div>
            @if (Model.State == "Pending")
            {
                <div class="pt-4">
                    <button class="btn btn-rounded mx-2"
                            data-toggle="modal"
                            data-target="#confirm-accept">
                        <i class="fa fa-check-circle pr-2"></i>
                        Accept
                    </button>
                </div>
                <div class="pt-4">
                    <button class="btn btn-rounded btn-danger mx-2"
                            data-toggle="modal"
                            data-target="#confirm-reject">
                        <i class="fa fa-times-circle pr-2"></i>
                        Reject
                    </button>
                </div>
            }
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th scope="col">Comments</th>
                        <th style="width: 20px"></th>
                    </tr>
                </thead>
                <tbody id="myBody">
                    @foreach (var comment in Model.Comments)
                    {
                    <tr>
                        <td>@comment.Text</td>
                        @using (Html.BeginForm("DeleteCommentAjax", "Application", new { comment.Id }, FormMethod.Post, null, new { style = "display:inline;", id="deleteForm" }))
                        {
                            @Html.AntiForgeryToken()
                            <td>
                                <button type="submit" class="btn btn-rounded btn-primary" id="deleteSubmit">
                                    <i class="fa fa-trash pr-2"></i>
                                    Delete
                                </button>
                            </td>
                        }
                    </tr>
                    }
                    </tbody>
                <tbody>
                    <tr>
                        @using (Html.BeginForm("CreateCommentAjax", "Application", null, FormMethod.Post, null, new { style = "display:inline;", id = "createForm" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(m => m.Id)
                            <td>
                                <div class="form-group">
                                    @Html.EditorFor(m => m.CommentText, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(m => m.CommentText)
                                </div>
                            </td>
                            <td>
                                <button type="submit" class="btn btn-rounded btn-primary" id="createSubmit">
                                    <i class="fa fa-check pr-2"></i>
                                    Comment
                                </button>
                            </td>
                        }
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="modal fade" id="confirm-accept" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Accept Application</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="font-weight-bold mb-0">Are you sure you want to accept this application?</p>
                <p class="text-danger mb-0"><small>This action cannot be undone.</small></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-rounded" data-dismiss="modal">
                    <i class="fa fa-chevron-left pr-2"></i>
                    Cancel
                </button>
                @using (Html.BeginForm("Accept", "Application", new { Model.Id }, FormMethod.Post, null, new { style = "display:inline;" }))
                {
                    @Html.AntiForgeryToken()
                    <button type="submit" class="btn btn-rounded btn-danger">
                        <i class="fa fa-check-circle pr-2"></i>
                        Accept
                    </button>
                }
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="confirm-reject" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Reject Application</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="font-weight-bold mb-0">Are you sure you want to reject this application?</p>
                <p class="text-danger mb-0"><small>This action cannot be undone.</small></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-rounded" data-dismiss="modal">
                    <i class="fa fa-chevron-left pr-2"></i>
                    Cancel
                </button>
                @using (Html.BeginForm("Reject", "Application", new { Model.Id }, FormMethod.Post, null, new { style = "display:inline;" }))
                {
                    @Html.AntiForgeryToken()
                    <button type="submit" class="btn btn-rounded btn-danger">
                        <i class="fa fa-times-circle pr-2"></i>
                        Reject
                    </button>
                }
            </div>
        </div>
    </div>
</div>
@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $(function () {
            $('#createSubmit').on('click', function (evt) {
                alert("I'm in");
                evt.preventDefault();
                $.post($('#createForm').attr("action"), $('#createForm').serialize(), function (data) {
                    alert("I'm in the function");
                    $('#myBody tr').remove();
                    $.each(data, function (i, emp) {
                        alert("I'm in the thing");
                        var $row = $('<tr/>');
                        $row.append($('<td/>').html(emp.commentText));
                        $('#myBody').append($row);
                    });
                });
            });
        });
    </script>
    <script>
        $(function () {
            $('#deleteSubmit').on('click', function (evt) {
                alert("I'm in");
                evt.preventDefault();
                $.post($('#deleteForm').attr("action"), $('#deleteForm').serialize(), function (data) {
                    alert("I'm in the function");
                    $('#myBody tr').remove();
                    $.each(data, function (i, emp) {
                        alert("I'm in the thing");
                        var $row = $('<tr/>');
                        $row.append($('<td/>').html(emp.commentText));
                        $('#myBody').append($row);
                    });
                });
            });
        });
    </script>
    }*@

MainApp/MainApp/Views/Application/Edit.cshtml
@model MainApp.Models.Application

@{
    ViewData["Title"] = "Edit application";
}

<div class="row">
    <div class="col-sm-12">
        <h2>Edit application</h2>
        @using (Html.BeginForm("Create"))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.Id)
            <div class="form-group">
                @Html.LabelFor(m => m.FirstName)
                @Html.EditorFor(m => m.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.LastName)
                @Html.EditorFor(m => m.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.PhoneNumber)
                @Html.EditorFor(m => m.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.PhoneNumber, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.EmailAddress)
                @Html.EditorFor(m => m.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.EmailAddress, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.ContactAgreement)
                @Html.EditorFor(m => m.ContactAgreement, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.ContactAgreement, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.TextBoxFor(m => m.File, new { type = "file" })
                @Html.ValidationMessageFor(m => m.File)
            </div>
            <a asp-area="" asp-controller="Application" asp-action="Index">
                <button type="button" class="btn btn-rounded btn-secondary mr-2">
                    <i class="fa fa-chevron-left pr-2"></i>
                    Cancel
                </button>
            </a>
            <button type="submit" class="btn btn-rounded btn-primary">
                <i class="fa fa-check pr-2"></i>
                Save
            </button>
        }
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}