MainApp/MainApp/Controllers/CandidateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MainApp.Models;
using MainApp.EntityFramework;
using Microsoft.EntityFrameworkCore;
using MainApp.Authorization;
using Microsoft.AspNetCore.Authorization;

namespace MainApp.Controllers
{
    public class CandidateController : Controller
    {
        private readonly DataContext _context;

        public CandidateController(DataContext context)
        {
            _context = context;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index([FromQuery(Name = "search")] string searchString)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            if (role != Role.ADMIN)
                return new UnauthorizedResult();
            if (string.IsNullOrEmpty(searchString))
                return View(await _context.Candidates.ToListAsync());

            List<Candidate> searchResult = await _context
                .Candidates
                .Where(o => o.LastName.Contains(searchString, StringComparison.OrdinalIgnoreCase))
                .ToListAsync();

            return View(searchResult);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> IndexAjax([FromQuery(Name = "search")] string searchString)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            if (role != Role.ADMIN)
                return new UnauthorizedResult();
            if (string.IsNullOrEmpty(searchString))
                return new JsonResult(await _context.Candidates.ToListAsync());

            List<Candidate> searchResult = await _context
                .Candidates
                .Where(o => o.LastName.Contains(searchString, StringComparison.OrdinalIgnoreCase))
                .ToListAsync();

            return new JsonResult(searchResult);
        }
        
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            string email = AuthorizationTools.GetEmail(User);
            Candidate us = _context.Candidates.Where(c => c.EmailAddress == email).First();
            if (role != Role.ADMIN && (us == null || us.Id != id.Value))
                return new UnauthorizedResult();

            if (id == null)
            {
                return BadRequest($"id shouldn't not be null");
            }
            var offer = await _context.Candidates.FirstOrDefaultAsync(x => x.Id == id.Value);
            if (offer == null)
            {
                return NotFound($"offer not found in DB");
            }
            return View(offer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Edit(Candidate model)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            string email = AuthorizationTools.GetEmail(User);
            Candidate us = _context.Candidates.Where(c => c.EmailAddress == email).First();
            if (role != Role.ADMIN && (us == null || us.Id != model.Id))
                return new UnauthorizedResult();

            if (!ModelState.IsValid)
            {
                return View();
            }

            var candidate = await _context.Candidates.FirstOrDefaultAsync(x => x.Id == model.Id);
            candidate.FirstName = model.FirstName;
            candidate.LastName = model.LastName;
            candidate.EmailAddress = model.EmailAddress;
            candidate.PhoneNumber = model.PhoneNumber;
            _context.Update(candidate);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", new { id = model.Id });
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Delete(int? id)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            if (role != Role.ADMIN)
                return new UnauthorizedResult();
            if (id == null)
            {
                return BadRequest($"id should not be null");
            }

            _context.Candidates.Remove(new Candidate() { Id = id.Value });
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Details(int id)
        {
            Role role = await AuthorizationTools.GetRoleAsync(User, _context);
            ViewData.Add("role", role);
            ViewData.Add("id", AuthorizationTools.GetUserDbId(User, _context, role));
            string email = AuthorizationTools.GetEmail(User);
            Candidate us = _context.Candidates.Where(c => c.EmailAddress == email).FirstOrDefault();
            if (role != Role.ADMIN && (us == null || us.Id != id))
                return new UnauthorizedResult();

            var candidate = await _context.Candidates
                .FirstOrDefaultAsync(x => x.Id == id);
            if (role == Role.ADMIN)
                return View("DetailsAdmin", candidate);
            return View("DetailsCandidate", candidate);
        }
    }
}

MainApp/MainApp/Views/Candidate/DetailsAdmin.cshtml
@model MainApp.Models.Candidate

@{
    ViewData["Title"] = Model.FirstName + " " + Model.LastName;
}

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="d-flex align-items-center">
            <div class="pr-3" style="font-size: 25px">
                <a href="@Url.Action("Index", "Candidate")">
                    <i class="fa fa-chevron-circle-left"></i>
                </a>
            </div>
            <h3 class="mb-1">
                Details
            </h3>
        </div>
    </div>
    <div class="pt-2">
        <div>
            <div class="offer-details">
                <h4 class="mb-0 mt-2">@(Model.FirstName + " " + Model.LastName)</h4>
                <label>First name:</label>
                <div class="content">@Model.FirstName</div>
                <label>Last name:</label>
                <div class="content">@Model.LastName</div>
                <label>Email adress:</label>
                <div class="content">@Model.EmailAddress</div>
                <label>Phone number:</label>
                <div class="content">@Model.PhoneNumber</div>
            </div>
        </div>
    </div>
</div>

MainApp/MainApp/Views/Candidate/DetailsCandidate.cshtml
@model MainApp.Models.Candidate

@{
    ViewData["Title"] = "My profile details";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="d-flex align-items-center">
            <h3 class="mb-1">
                Details
            </h3>
        </div>
    </div>
    <div class="pt-2">
        <div>
            <div class="offer-details">
                <h4 class="mb-0 mt-2">@(Model.FirstName + " " + Model.LastName)</h4>
                <label>First name:</label>
                <div class="content">@Model.FirstName</div>
                <label>Last name:</label>
                <div class="content">@Model.LastName</div>
                <label>Email adress:</label>
                <div class="content">@Model.EmailAddress</div>
                <label>Phone number:</label>
                <div class="content">@Model.PhoneNumber</div>
                <div class="pt-4">
                    <a asp-controller="Candidate" asp-action="Edit" asp-route-id="@Model.Id">
                        <button class="btn btn-rounded btn-primary mx-2">
                            <i class="fa fa-edit pr-2"></i>
                            Edit
                        </button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

MainApp/MainApp/Views/Candidate/Edit.cshtml
@model Candidate
@{
    ViewBag.Title = "Edit";
}
<div class="row">
    <div class="col-sm-12">
        <h2>Edit candidate profile</h2>
        @using (Html.BeginForm("Create"))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.EmailAddress)
            <div class="form-group">
                @Html.LabelFor(m => m.LastName)
                @Html.EditorFor(m => m.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.LastName)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.FirstName)
                @Html.EditorFor(m => m.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.FirstName)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.PhoneNumber)
                @Html.EditorFor(m => m.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.PhoneNumber)
            </div>
            <a asp-area="" asp-controller="Candidate" asp-action="Details" asp-route-id="@Model.Id" >
                <button type="button" class="btn btn-rounded btn-secondary mr-2">
                    <i class="fa fa-chevron-left pr-2" ></i>
                    Cancel
                </button>
            </a>
            <button type="submit" class="btn btn-rounded btn-primary">
                <i class="fa fa-check pr-2" ></i>
                Save
            </button>
        }
    </div>
</div> 

MainApp/MainApp/Views/Candidate/Index.cshtml
@model IEnumerable<MainApp.Models.Candidate>

@{
    ViewData["Title"] = "Candidates";
}

<div class="row page-box">
    <div class="col-sm-12">
        <div class="table-title">
            <div class="row">
                <div class="col-12 col-md-4 d-flex align-items-center py-2">
                    <h3 class="font-weight-bold mb-0">
                        Candidate list
                    </h3>
                    <div>
                        <span class="badge badge-pill badge-primary align-top">
                            @Model.Count()
                        </span>
                    </div>
                </div>
                <div class="col-12 col-md-4 py-2">
                    @using (Html.BeginForm("IndexAjax", "Candidate", FormMethod.Get))
                    {
                        <div class="input-group search-input"
                             style="border-radius: 20px">
                            <input name="search"
                                   type="text"
                                   class="form-control"
                                   placeholder="Search by last name.."
                                   aria-label="Search by last name"
                                   aria-describedby="button-search">
                            <div class="input-group-append">
                                <button id="button-search"
                                        class="btn btn-primary"
                                        type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">First name</th>
                    <th scope="col">Last name</th>
                    <th scope="col">Email address</th>
                    <th scope="col">Phone number</th>
                    <th style="width: 20px"></th>
                </tr>
            </thead>
            <tbody id="myBody">
                @foreach (var hr in Model.OrderBy(h => h.LastName))
                {
                    <tr>
                        <td>@Html.ActionLink(hr.FirstName, "Details", new { id = hr.Id })</td>
                        <td>@Html.ActionLink(hr.LastName, "Details", new { id = hr.Id })</td>
                        <td>@hr.EmailAddress</td>
                        <td>@hr.PhoneNumber</td>
                    </tr>
                }

            </tbody>
        </table>

    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $(function () {
            $('#button-search').on('click', function (evt) {
                evt.preventDefault();
                $.get("https://localhost:44391/Candidate/IndexAjax", $('form').serialize() ,function (data) {
                    $('#myBody tr').remove();
                    $.each(data, function (i, emp) {
                        var $row = $('<tr/>');
                        $row.append($('<td><a href="/Candidate/Details/1">' + emp.firstName + '</a></td>'));
                        $row.append($('<td><a href="/Candidate/Details/1">' + emp.lastName + '</a></td>'));
                        $row.append($('<td/>').html(emp.emailAddress));
                        $row.append($('<td/>').html(emp.phoneNumber));
                        $('#myBody').append($row);
                    });
                });
            });
        });
    </script>
}